const express = require('express');
const db = require('../config/connection');
const {User, Thought} = require('../models')

const app = express();

db.once('open', async () => {
    console.log('connected')

    await User.deleteMany({});

    await Thought.deleteMany({});

    // const Users = [];

    // Users.push({
    //     username,
    //     email,
    //     thought,
    //     friend
    // })

    // create your own autogenerated id to link thoughts to users

    const users = [
        {
            username: 'iamincognito123',
            email: 'anhvudnguyen27@gmail.com',
        },
        {
            username: 'thebigapple',
            email: 'apple@gmail.com',
        },
        {
            username: 'thebigticket',
            email: 'tickets@gmail.com',
        }

    ]

    const thoughts = [
        {
            username: 'iamincognito123',
            thoughtText: 'hello world',
            reactions: {
                reactionBody: 'omygod',
            }
        },
        {
            username: 'thebigapple',
            thoughtText: 'hi what is your name',
            reactions: {
                reactionBody: 'cars'
            }
        },
        {
            username: 'thebigticket',
            thoughtText: 'whatsup brodie',
            reactions: {
                reactionBody: 'yuh'
            }
        },
    ]



    await User.collection.insertMany(users)

    await Thought.collection.insertMany(thoughts)

    console.info('Seeding complete! 🌱');
    process.exit(0);
})